// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiqvdtsyiyunwmbsidcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppcXZkdHN5aXl1bndtYnNpZGNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTU4NDUsImV4cCI6MjA2MTc3MTg0NX0.kHu81vmxl9gfcmPXE6plN-VHboM9jBhSj0NPGjdOLHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);