
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcwzzdnkciqautrkbchu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxjd3p6ZG5rY2lxYXV0cmtiY2h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDgwODIyNTcsImV4cCI6MjAyMzY1ODI1N30.d6yRRQT4Uh0HqqJ2FkNYhnJ5WDWH2bAuT33ePgdXGNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
